# Generated by Django 4.2.3 on 2023-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0003_etf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etf',
            name='precio_a_comprar',
        ),
        migrations.AddField(
            model_name='etf',
            name='precioTarget',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='etf',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='etf',
            name='subyacente',
            field=models.CharField(max_length=10),
        ),
    ]
