# Generated by Django 4.2.3 on 2023-08-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0004_remove_etf_precio_a_comprar_etf_preciotarget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bkn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=50)),
            ],
        ),
    ]
